version: '3.9'

services:
  db:
    container_name: 'db'
    image: postgres:15.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

  web:
    container_name: 'web'
    image: alexanderpai/workbook:latest
    restart: always
    volumes:
      - static_value:/app/src/static/
      - media_value:/app/src/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "cd ./src &&
             python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0:8000"
  nginx:
    container_name: 'nginx'
    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    # command: certonly --webroot --webroot-path=/var/www/certbot/ --email lawlikeart@yandex.ru --agree-tos --no-eff-email -d backendpages.ru -d www.backendpages.ru
    depends_on:
      - nginx


volumes:
  db_volume:
  static_value:
  media_value:
