# Generated by Django 5.0.2 on 2024-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет текста'),
        ),
    ]
