# Generated by Django 5.0.2 on 2024-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_background_color_tag_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text_color',
            field=models.CharField(blank=True, choices=[('white', '#FFFFFF'), ('black', '#000000')], default='white', max_length=200, null=True, verbose_name='Цвет текста'),
        ),
    ]
