# Generated by Django 5.0.2 on 2024-02-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.TagArticle', to='articles.tag'),
        ),
    ]
