# Generated by Django 5.0.2 on 2024-02-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='blue', max_length=200, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_color',
            field=models.CharField(choices=[('white', '#FFFFFF'), ('black', '#000000')], default='white', max_length=200, verbose_name='Цвет текста'),
        ),
    ]
